import { Bitcount_Grid_Single, Ubuntu_Mono } from "next/font/google";
import "./globals.css";

const bitcount = Bitcount_Grid_Single({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--font-bitcount",
  display: "swap",
});
const ubuntu = Ubuntu_Mono({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-ubuntu",
  display: "swap",
});

export const metadata = {
  title: "Wajiha's Portfolio",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth dark">
      <body
        className={`${ubuntu.variable} ${bitcount.variable} font-ubuntu antialiased dark:bg-dark-200 dark:text-white overflow-x-hidden leading-8`}
      >
        {children}
      </body>
    </html>
  );
}
